// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsUgoG2GGPl1QI8tFAZBNkFXGC6qE8N1k',
    appId: '1:796086575750:web:9db81cadf175bb6fab6707',
    messagingSenderId: '796086575750',
    projectId: 'todolista3-9c3b9',
    authDomain: 'todolista3-9c3b9.firebaseapp.com',
    storageBucket: 'todolista3-9c3b9.firebasestorage.app',
    measurementId: 'G-C5SRMDPVYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOu0IlWMUsk6dXzMe3A1OsCV5BT1DYd28',
    appId: '1:796086575750:android:31b77d09638e1f31ab6707',
    messagingSenderId: '796086575750',
    projectId: 'todolista3-9c3b9',
    storageBucket: 'todolista3-9c3b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7csx5Z8saZLxdhZfDDRxj7BbH6rUpNz8',
    appId: '1:796086575750:ios:d0adc26afc8bb269ab6707',
    messagingSenderId: '796086575750',
    projectId: 'todolista3-9c3b9',
    storageBucket: 'todolista3-9c3b9.firebasestorage.app',
    iosBundleId: 'com.todolista3.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7csx5Z8saZLxdhZfDDRxj7BbH6rUpNz8',
    appId: '1:796086575750:ios:d0adc26afc8bb269ab6707',
    messagingSenderId: '796086575750',
    projectId: 'todolista3-9c3b9',
    storageBucket: 'todolista3-9c3b9.firebasestorage.app',
    iosBundleId: 'com.todolista3.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsUgoG2GGPl1QI8tFAZBNkFXGC6qE8N1k',
    appId: '1:796086575750:web:87fdd7bd44b45069ab6707',
    messagingSenderId: '796086575750',
    projectId: 'todolista3-9c3b9',
    authDomain: 'todolista3-9c3b9.firebaseapp.com',
    storageBucket: 'todolista3-9c3b9.firebasestorage.app',
    measurementId: 'G-LSM0WLMXEQ',
  );
}
